name = "mood-board"
main = "functions/index.js"
compatibility_date = "2026-05-31"

[[d1_databases]]
binding = "DB"
database_name = "mood-projects"
database_id = "97075942-c155-4a21-a11f-433dbda9d1aa"

[vars]
ENVIRONMENT = "production"
